IF(HAVE_QTXLSX)
    RETURN()
ENDIF()

CMAKE_MINIMUM_REQUIRED(VERSION 3.11)


# 最顶层CMakeLists.txt文件所在的路径
MESSAGE(STATUS "CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}")
# 当前的CMakeLists.txt文件所在的路径
MESSAGE(STATUS "CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
# 当前的QtXlsx.cmake文件所在的路径
MESSAGE(STATUS "CMAKE_CURRENT_LIST_DIR: ${CMAKE_CURRENT_LIST_DIR}")

GET_FILENAME_COMPONENT(QTXLSX_DIR "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
MESSAGE(STATUS "SOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR} CMAKE_CURRENT_LIST_DIR=${CMAKE_CURRENT_LIST_DIR} QTXLSX_DIR=${QTXLSX_DIR}")
IF((NOT EXISTS "${QTXLSX_DIR}/src") OR (NOT EXISTS "${QTXLSX_DIR}/include") OR (NOT EXISTS "${QTXLSX_DIR}/CMakeLists.txt"))
    MESSAGE(FATAL_ERROR "QTXLSX_DIR NOT FOUND: SOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR} QTXLSX_DIR=${QTXLSX_DIR}")
ENDIF()

#配置阶段构建依赖
include(FetchContent)

FetchContent_Declare(QtXlsx
    SOURCE_DIR ${QTXLSX_DIR}
)

FetchContent_MakeAvailable(QtXlsx)

SET(HAVE_QTXLSX TRUE)
